# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  port = 8910
  apiProxyPath = "/api"
  title = "Watch That Name"
  includeEnvironmentVariables = ['CLERK_FRONTEND_API_URL', 'PLAUSIBLE_DOMAIN']
[api]
  port = 8911
  includeEnvironmentVariables = ['CLERK_API_KEY', 'GODADDY_KEY', 'GODADDY_SECRET']
[browser]
  open = true
[experimental]
  esbuild = false
